In [1]:
import tensorflow as tf

In [4]:
# 0阶张量
mammal = tf.Variable('Elephant', tf.string)
ignition = tf.Variable(451, tf.int16)
floating = tf.Variable(3.1415926, tf.float64)
its_complicated = tf.Variable(12.3 - 4.85j, tf.complex64)

In [5]:
[mammal, ignition, floating, its_complicated]

[<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Elephant'>,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=451>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.1415925>,
 <tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(12.3-4.85j)>]

In [6]:
# 1阶张量
mystr = tf.Variable(['Hello', 'World'], tf.string)
cool_numbers = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.58j, 7.5 - 6.23j], tf.complex64)

In [7]:
[mystr, cool_numbers, first_primes, its_very_complicated]

[<tf.Variable 'Variable:0' shape=(2,) dtype=string, numpy=array([b'Hello', b'World'], dtype=object)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([3.14159, 2.71828], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 2,  3,  5,  7, 11], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([12.3-4.58j,  7.5-6.23j])>]

In [8]:
# 2阶张量
mymat = tf.Variable([[7],  [11]], tf.int16)
myxor = tf.Variable([[False, True], [True, False]], tf.bool)
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
squarish_squares = tf.Variable([[4, 9], [16, 25]], tf.int32)
rank_of_squares = tf.rank(squarish_squares)
mymatC = tf.Variable([[7], [11]], tf.int32)

In [9]:
[mymat, myxor, linear_squares, squarish_squares, rank_of_squares, mymatC]

[<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
 array([[ 7],
        [11]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=bool, numpy=
 array([[False,  True],
        [ True, False]])>,
 <tf.Variable 'Variable:0' shape=(4, 1) dtype=int32, numpy=
 array([[ 4],
        [ 9],
        [16],
        [25]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[ 4,  9],
        [16, 25]], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
 array([[ 7],
        [11]], dtype=int32)>]

In [10]:
# 4阶张量
my_image = tf.zeros([10, 299, 299, 3]) # batch * height * width * color

In [11]:
my_image

<tf.Tensor: shape=(10, 299, 299, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


 